
- name: Install nginx
  apt:
    name:
      - nginx

- name: Install Avahi for easy VM access when doing local development
  apt:
    name: "avahi-daemon"
    state: present
  notify:
    - restart avahi-daemon
  when: is_dev_environment == True

- name: Set dev hostname (to expose machine via Avahi)
  hostname:
    name: nateeag
  notify:
    - restart avahi-daemon
  when: is_dev_environment == True

- name: Make www.nateeag.com's webserver config available
  template:
    src: "{{ role_path }}/templates/etc/nginx/sites-available/nateeag.com.conf"
    dest: /etc/nginx/sites-available/nateeag.com.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart webserver

- name: Activate www.nateeag.com's webserver configuration
  file:
    path: /etc/nginx/sites-enabled/nateeag.com.conf
    src: /etc/nginx/sites-available/nateeag.com.conf
    state: link
  notify:
    - restart webserver
