
- name: Install nginx
  apt:
    name:
      - nginx

- name: Install Avahi for easy VM access when doing local development
  apt:
    name: "avahi-daemon"
    state: present
  notify:
    - restart avahi-daemon
  when: is_dev_environment == True

- name: Set dev hostname (to expose machine via Avahi)
  hostname:
    name: nateeag
  notify:
    - restart avahi-daemon
  when: is_dev_environment == True
